name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
    
    - name: Install dependencies
      run: rye sync
    
    - name: Run pytests via Rye
      run: rye test